[ATOM-16287] Validate Alignment Across All floatRxC
o3de/o3de-azslc pull request #5
Opened 2021-08-31 18:53 UTC by galibzon

[ATOM-16287] Validate Alignment Across All floatRxC
Between vulkan & dx12

This is v1.7.28

This is the exhaustive solution to the SRG Layout data alignment problem
when there are
float or float2 variables
preceded by matrices or structs that end in matrices of type:
float2x2, float3x2, float4x2
In such case the "float" or "float2" must be prepadded by a float3
variable.

The other cases are when
"float" type variables
are preceded by matrices or structs that end in matrices of type:
float2x3, float3x3, float4x3
In such case the "float" must be prepadded by a float2 variables.

Signed-off-by: garrieta <garrieta@amazon.com>

2021-09-01 22:25 UTC, santorac requested changes

2021-09-01 22:25 UTC, santorac commented on src/AzslcIntermediateRepresentation.cpp
> +            else // if (parentKindInfo->IsKindOneOf(Kind::ShaderResourceGroup))
Delete commented out code.

2021-09-01 22:47 UTC, galibzon commented on src/AzslcIntermediateRepresentation.cpp
> +            else // if (parentKindInfo->IsKindOneOf(Kind::ShaderResourceGroup))
It's supposed to be a comment :-)
Replaced with the comment:
// Due to similar check done above, it is a ShaderResourceGroup

2021-09-02 00:34 UTC, santorac approved these changes

2021-09-14 12:12 UTC, galibzon commented
Will close this pull request per our latest decision to mark it as an error for the user, proposing solutions and providing a command line argument to bypass error checking for this issue.

2021-09-14 12:12 UTC, closed without merging