Fix usage of `exportKeywords.py` by using the correct flags
o3de/o3de-azslc pull request #52
Opened 2022-07-22 12:14 UTC by martinwinter-huawei

Signed-off-by: Martin Winter <martin.winter@huawei.com>

The `exportKeywords.py` script can be used to generate a list of predefined types. The current state did not have a variable set (`silent` was not set but `False` passed directly) and the argument parser did not properly receive the `--listpredefined` flag, hence always crashed.

2022-08-03 04:13 UTC, siliconvoodoo requested changes
remove useless silent = False declaration in testfuncs.py

2022-08-03 04:13 UTC, siliconvoodoo commented on tests/testfuncs.py
> +    stdout, stderr, code = launchCompiler(compilerPath, ["--listpredefined"], silent)
I hope you can see that this is a trivially useless change :)

2022-08-03 04:13 UTC, siliconvoodoo commented on src/AzslcMain.cpp
> +    cli.add_flag("--listpredefined", listPredefined, "Output a list of all predefined types in AZSLang.");
ok. this is the real fix. good find.

2022-08-03 06:27 UTC, martinwinter-huawei commented on tests/testfuncs.py
> +    stdout, stderr, code = launchCompiler(compilerPath, ["--listpredefined"], silent)
good point!

2022-08-03 07:20 UTC, siliconvoodoo approved these changes
good for me

2022-08-03 07:20 UTC, siliconvoodoo commented on tests/testfuncs.py
> -        if not silent: print (clr.fg.RED + "compilation failed" + clr.style.RESET_ALL)
I see. missed that one. good job.

2022-09-12 15:56 UTC, jeremyong-az approved these changes

2022-09-12 16:04 UTC, galibzon approved these changes

2022-09-12 16:04 UTC, merged